nodeLinker: node-modules

npmPublishAccess: "restricted"
npmPublishRegistry: "https://npm.pkg.github.com"
npmAuthToken: "${NPM_TOKEN}"

npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"

npmScopes:
  worx-to:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "${NPM_TOKEN}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
