name: "Publish"
description: "Publish package to github npm repository"
inputs:
  version:
    required: true
  token:
    required: true
  defaultBranchName:
    default: "master"
    required: false
outputs:
  version:
    description: "final version"
    value: ${{ steps.version.outputs.version }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: "16.x"
        registry-url: "https://npm.pkg.github.com"
        scope: "@worx-to"

    - name: Get version
      shell: bash
      id: version
      run: |
        if ${{ github.ref_name == inputs.defaultBranchName }}
        then
          echo "::set-output name=version::${{ inputs.version }}"
        else
          echo "::set-output name=version::$(node -p -e 'require(`./package.json`).version.replace(/(\d+\.\d+\.\d+)(.*)/, `$1`) + `-` + `${{ github.ref_name }}`.replace(/[-_\/]+/g, `.`)').${{ inputs.version }}"
        fi

    - uses: rubenesp87/semver-validation-action@0.0.6
      name: Semver validation
      with:
        version: ${{ steps.version.outputs.version }}

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable --inline-builds

    - name: Set version
      shell: bash
      run: yarn uver -v ${{ steps.version.outputs.version }}

    - name: Build package
      shell: bash
      run: yarn build

    - run: yarn npm publish
      shell: bash
